version: 2
jobs:
  build:
    working_directory: ~/ros-training
    docker:
      - image: node:latest
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
    steps:
      # Install cask
      - checkout
      - run: git config --global user.name "$GIT_USERNAME" && git config --global user.email "$GIT_EMAIL"
      - run: git clone "$CIRCLE_REPOSITORY_URL" html && cd html && git checkout gh-pages && rm -fr * && cd ..
      - run: npm install -g reveal-md
        # Generate build files to /html
      - run: cd slides && reveal-md -w ./ --static ../html
      - deploy:
          name: Deploy to github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            cd html && git add -A && git commit -m "Autoupdate html sources" || true && git push https://$GH_TOKEN@github.com/RoboJackets/ros-training gh-pages || true
            fi
